In [6]:
import numpy as np
import pandas as pd

In [7]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [8]:
df = pd.read_csv('gurgaon_properties.csv')

In [9]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [10]:
df.tail()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
3956,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.20,6875.0,3200.0,Plot area 3200(297.29 sq.m.),12,12,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",6.0,North,0 to 1 Year Old,"['Huda city centre metro station', 'Sector 42-...",Current rental from this building is 1.65 lakh...,"['12 Fan', '1 Fridge', '1 Exhaust Fan', '12 Ge...","['Maintenance Staff', 'False Ceiling Lighting'...","['Environment5 out of 5', 'Safety4.5 out of 5'..."
3957,3 BHK Flat in Sector 77 Gurgaon,flat,Umang Winter Hills3.9 ★,1.10,5296.0,2077.0,Super Built up area 2077(192.96 sq.m.)Carpet a...,3,4,3+,servant room,"Sector 77 Gurgaon, Gurgaon, Haryana",9.0,North,1 to 5 Year Old,"['Entertainland Mall', 'Delhi Jaipur Expresswa...",Looking for a 3 bhk property for sale in gurga...,"['1 Wardrobe', '1 Fan', '1 Geyser', '1 Light',...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
3958,4 BHK Flat in Sector 70 Gurgaon,flat,Tulip Ivory3.5 ★,2.35,9791.0,2400.0,Carpet area: 2400 (222.97 sq.m.),4,4,3+,servant room,"Sector 70 Gurgaon, Gurgaon, Haryana",8.0,West,5 to 10 Year Old,"['Reach 3 Roads Shopping Mall', 'Southern Peri...","Corner building, sun facing, cross ventilation...","['1 Light', '1 Wardrobe', 'No AC', 'No Bed', '...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area3.5 out of 5', 'Construction3.5 ou..."
3959,3 BHK Flat in Sector 90 Gurgaon,flat,Shree Vardhman Flora3.8 ★,0.85,4404.0,1930.0,Super Built up area 1930(179.3 sq.m.)Carpet ar...,3,4,3,"servant room,store room","305, Sector 90 Gurgaon, Gurgaon, Haryana",3.0,South-East,1 to 5 Year Old,"['IRIS Broadway Mall', 'Dwarka Expressway', 'S...",One of the best location of the society with g...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction5 out of..."
3960,2 BHK Flat in Sector 82 Gurgaon,flat,Vatika The Seven Lamps3.8 ★,0.81,6192.0,1308.0,Super Built up area 1300(120.77 sq.m.),2,2,2,not available,"Sector 82 Gurgaon, Gurgaon, Haryana",15.0,West,1 to 5 Year Old,"['SS Omnia Mall', 'Golf Course Ext Rd', 'Knowl...","Brokers excuse, 2bhk,1300 sq. Ft., east facing...","['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction5 out of..."

In [11]:

df.shape

(3961, 20)

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [14]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [15]:

df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in DLF Phase 1,house,dlf city plots,13.50,29880.0,4518.0,Plot area 502(419.74 sq.m.),5,5,2,"study room,servant room,others","A801, DLF Phase 1, Gurgaon, Haryana",2.0,East,5 to 10 Year Old,"['Phase 2 Metro Station', 'Grand Mall', 'Jacar...",Beautiful house at very prime location in dlf ...,"['5 Fan', '1 Exhaust Fan', '5 Geyser', '14 Lig...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1,4 BHK Flat in Sector 69 Gurgaon,flat,Tulip Violet4.3 ★,1.70,8457.0,2010.0,Super Built up area 2010(186.74 sq.m.),4,4,2,not available,"104, Sector 69 Gurgaon, Gurgaon, Haryana",1.0,South,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",This lovely 4 bhk apartment/flat in sector 69 ...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4 out of..."
2,2 BHK Flat in Sohna,flat,HCBS Sports Ville3.6 ★,0.32,4301.0,744.0,Built Up area: 743.99 (69.12 sq.m.),2,2,1,not available,"Sohna, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['The roadside cafe', 'GD Goenka Mess', 'ROyal...","Spacious rooms, big balcony, beautiful balcony...",NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area4 out of 5', 'Construction4 out of..."
3,4 BHK Flat in Gwal Pahari,flat,Paras Quartier,5.90,11028.0,5350.0,Super Built up area 5350(497.03 sq.m.),4,4,3+,"pooja room,study room,servant room,store room","Gwal Pahari, Gurgaon, Haryana",19.0,East,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'Ambience Mall'...","New apartment, lush green aravalli valley 270 ...","['4 Fan', '1 Exhaust Fan', '10 Light', '5 AC',...","['Centrally Air Conditioned', 'Security / Fire...",NaN
4,4 Bedroom House for sale in Sector 4 Gurgaon,house,independent,2.30,17014.0,1352.0,Plot area 160(133.78 sq.m.),4,4,3,not available,"Sector 4 Gurgaon, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Kr D...",Kothi for sale in sector 4 gurgaon at an very ...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Park', 'Visitor Parking', 'Club house / Comm...","['Environment5 out of 5', 'Safety5 out of 5', ..."

In [16]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [17]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in DLF Phase 1,house,dlf city plots,DLF Phase 1,13.50,29880.0,4518.0,Plot area 502(419.74 sq.m.),5,5,2,"study room,servant room,others","A801, DLF Phase 1, Gurgaon, Haryana",2.0,East,5 to 10 Year Old,"['Phase 2 Metro Station', 'Grand Mall', 'Jacar...",Beautiful house at very prime location in dlf ...,"['5 Fan', '1 Exhaust Fan', '5 Geyser', '14 Lig...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1,4 BHK Flat in Sector 69 Gurgaon,flat,Tulip Violet4.3 ★,Sector 69,1.70,8457.0,2010.0,Super Built up area 2010(186.74 sq.m.),4,4,2,not available,"104, Sector 69 Gurgaon, Gurgaon, Haryana",1.0,South,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",This lovely 4 bhk apartment/flat in sector 69 ...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4 out of..."
2,2 BHK Flat in Sohna,flat,HCBS Sports Ville3.6 ★,Sohna,0.32,4301.0,744.0,Built Up area: 743.99 (69.12 sq.m.),2,2,1,not available,"Sohna, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['The roadside cafe', 'GD Goenka Mess', 'ROyal...","Spacious rooms, big balcony, beautiful balcony...",NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area4 out of 5', 'Construction4 out of..."
3,4 BHK Flat in Gwal Pahari,flat,Paras Quartier,Gwal Pahari,5.90,11028.0,5350.0,Super Built up area 5350(497.03 sq.m.),4,4,3+,"pooja room,study room,servant room,store room","Gwal Pahari, Gurgaon, Haryana",19.0,East,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'Ambience Mall'...","New apartment, lush green aravalli valley 270 ...","['4 Fan', '1 Exhaust Fan', '10 Light', '5 AC',...","['Centrally Air Conditioned', 'Security / Fire...",NaN
4,4 Bedroom House for sale in Sector 4 Gurgaon,house,independent,Sector 4,2.30,17014.0,1352.0,Plot area 160(133.78 sq.m.),4,4,3,not available,"Sector 4 Gurgaon, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Kr D...",Kothi for sale in sector 4 gurgaon at an very ...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Park', 'Visitor Parking', 'Club house / Comm...","['Environment5 out of 5', 'Safety5 out of 5', ..."

In [18]:
df['sector'] = df['sector'].str.lower()

In [19]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [20]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','sector 6')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [21]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','sector 42')

In [22]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [23]:
df['sector'] = df['sector'].str.replace('sohna road road','47')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [24]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [25]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [26]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [27]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 90                      90
sector 65                      90
sector 81                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 37d                     68
sector 86                      67
sector 50                      65
sector 107                     60
sector 108                     59
sector 95                      57
sector 56                      57
sector 48                      56
sector 89                      56
sector 2                       55
sector 70a                     54
sector 70                      53
sector 43                      53
sector 37c                     53
sector-33 sohna road           51
sector 84                      51
sector 26                      50
sector 67                      48
sector 49                      48
sector 28                      47
sector 66                      46
sector 103                     45
sector 25                      43
sector 113                     43
sector 61                      42
sector 82                      42
sector 7                       39
sector 106                     38
sector 4                       36
sector 99a                     32
sector 54                      31
sector 12                      30
sector 68                      30
sector 77                      29
sector 72                      29
sector 71                      27
sector 24                      24
sector 57                      24
sector 112                     24
sector 88a                     23
sector 105                     23
sector 14                      23
sector 33                      23
sector 67a                     22
sector 111                     22
sector 11                      21
sector 22                      20
sector 82a                     20
sector 3                       20
sector 78                      19
sector 47                      19
sector 74                      18
sector 63a                     18
sector 91                      17
sector 62                      17
sector 6                       17
sector 110                     16
sector 99                      16
sector 60                      15
sector 63                      15
gwal pahari                    14
sector 55                      14
sector 76                      14
sector 52                      14
sector 53                      14
sector 1 sector 6              14
sector 4 phase 2               13
sector 36a                     13
sector 46                      13
sector 9                       13
sector 39                      12
sohna road road                12
sector 31                      12
sector 38                      12
sector 93                      12
sector 9a                      11
sector 41                      11
sector 3 phase 3 extension     11
sector 1a sector 6             10
sector 13                      10
sector 95a                      9
sector 45                       9
sector 3 phase 2                9
sector 10a                      8
sector 2 extension              8
sector 23                       8
sector 59                       8
sector 89 a                     8
sector 40                       8
c block sector 43               8
sector 17                       8
dwarka expressway               8
sector 8                        8
sector 58                       7
sector 51                       7
sector 36 sohna road            7
sector 21                       6
sector 5                        6
sector 1                        6
manesar                         5
sector 23a                      5
new sector 2                    5
sector 80                       5
sector 42                       5
sector 30                       5
new                             4
sector 12a                      4
sector 3a                       4
sector 36                       4
sector 88b                      3
b block sector 43               3
sector 15                       3
sector 110 a                    3
sector 17a                      3
sector 17b                      3
sector 73                       3
patel nagar                     3
maruti kunj                     3
a block sector 43               3
sector 27                       3
Name: count, dtype: int64

In [28]:
df['sector'] = df['sector'].astype(str)
df['sector'] = df['sector'].fillna('').astype(str)
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace(['sector 3 phase 3 extension','sector 3 phase 3 extension'],'sector 43')
df['sector'] = df['sector'].fillna('').astype(str)

In [29]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')
df['sector'] = df['sector'].str.replace('sector 37d','sector 37')
df['sector'] = df['sector'].str.replace('sector 67a','sector 67')
df['sector'] = df['sector'].str.replace('sector 82a','sector 82')
df['sector'] = df['sector'].str.replace('sector 36a','sector 36')

In [30]:
df['sector'] = df['sector'].str.replace('sector 37a','sector 37')
df['sector'] = df['sector'].str.replace('sector 37c','sector 37')
df['sector'] = df['sector'].str.replace('sector 70a','sector 70')
df['sector'] = df['sector'].str.replace('sector 99a','sector 99')
df['sector'] = df['sector'].str.replace('sector 88a','sector 88')
df['sector'] = df['sector'].str.replace('sector 63a','sector 63')
df['sector'] = df['sector'].str.replace('sector 36aa','sector 36')
df['sector'] = df['sector'].str.replace('sector 9a','sector 9')
df['sector'] = df['sector'].str.replace('sector 17a','sector 17')
df['sector'] = df['sector'].str.replace('sector 10a','sector 10')
df['sector'] = df['sector'].str.replace('sector 17b','sector 17')                         
df['sector'] = df['sector'].str.replace('sector 88b','sector 88')

In [31]:
df[df['sector'] == 'new']

Empty DataFrame
Columns: [property_name, property_type, society, sector, price, price_per_sqft, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [32]:
df.loc[955,'sector'] = 'sector 37'
df.loc[2800,'sector'] = 'sector 92'
df.loc[2838,'sector'] = 'sector 90'
df.loc[2857,'sector'] = 'sector 76'

In [33]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [36]:
df.loc[[311,1072,1486,3040,3875],'sector'] = 'sector 110'

In [41]:
df.isnull().sum()

property_type         0
society               1
sector                0
price                18
price_per_sqft       18
area                 18
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
floorNum             19
facing             1105
agePossession         1
nearbyLocations     177
furnishDetails      981
features            635
dtype: int64

In [42]:
# feature engineering required -> areaWithType, additionalRoom, facing, agePossession, furnishDetails, features
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)